### ISSUE TITLE
Chapter 3.0 page links to Chapter 6.0

### ISSUE THREAD

**Issue by 3mrsh** [neonwatty/machine-learning-refined#10]
Hey Professors,

The Chapter 3 Section 0 link on the `index.html` file leads to [a page ](https://jermwatt.github.io/mlrefined/blog_posts/3_First_order_methods/3_0_Introduction.html)titled "6.0 Introduction". However, the contents of that page make sense for the introduction of Chapter 3. I think it could be that the title is incorrect whereas the contents are correct

**Comment by neonwatty** [comment]
thanks - corrected.
