### ISSUE TITLE
Great work!

### ISSUE THREAD

**Issue by TaiChiTiger** [neonwatty/machine-learning-refined#12]
Your work build a bridge between machine learning and math, and provide a good intuition for machine learning. So when will your second book come out?

**Comment by nicholashub** [comment]
I'll second that. The book is such a gem! Also wondering if you'll be working on the uncompleted Notes section on the homepage! @jermwatt

**Comment by neonwatty** [comment]
Very happy to hear you find our book useful!   It's truly a labor of love.

The second edition will be coming out later this year!  I'll make sure to let you know when it is released.

Yes @nicholashub - as the publication date approaches the Notes section will be expanded - and slideshow presentations will be added!

**Comment by neonwatty** [comment]
PS: @TaiChiTiger @nicholashub  If you have a moment, could you please rate / briefly review the first edition of our text on Amazon (https://amzn.to/2U95UCV) or your favorite book review site?  (Reviews on Amazon can be made even if you purchased the text elsewhere, or were given a copy by someone, etc.,!)

These reviews go a long way to helping us get our text in front of new potential readers who we think will love it once they crack it open!   This goes double for the forthcoming 2nd edition!!!

**Comment by nicholashub** [comment]
Just added the [review](https://www.amazon.com/gp/customer-reviews/R2GNQTDJRM31SW/ref=cm_cr_othr_d_rvw_ttl?ie=UTF8&ASIN=B01L27MRMI)! BTW, is it intentional that the solutions to the exercises in the book are not provided?

**Comment by neonwatty** [comment]
Thanks so much! 

Yes - no solutions in the back (a standard with our publisher).  However if you are not enrolled in a university course using the text I can provide you with solutions to the first edition if you email me at jermwatt@gmail.com!

**Comment by TaiChiTiger** [comment]
I'm reading the first version of your book, it helps me a lot. When I finished, I will add a review in both Chinese and English on Amazon.

**Comment by neonwatty** [comment]
Thanks!
