### ISSUE TITLE
solution to exercises?

### ISSUE THREAD

**Issue by randomgambit** [neonwatty/machine-learning-refined#13]
Hello there! This is a really great book! However I am not able to find the solution to the mathematical exercises... Where are they?

Thanks!

**Comment by neonwatty** [comment]
Hi!  Thanks for your kind words!  

Our publisher distributes solutions to the mathematical (and coding) exercises.  If you shoot me an email at jermwatt@gmail.com I will connect you with the appropriate contact!

**Comment by sergiovasquez122** [comment]
Hello!

I was wondering if those who purchased the book who are not instructors would be able to obtain a copy of the solution manual as well. I own the 1st and 2nd editions of your books and would like to verify my work if I could. Thank you for all the hard work! One of the best books I have read in any field.
