### ISSUE TITLE
Solutions to exercises on Cambridge Resources site missing

### ISSUE THREAD

**Issue by allejanvanderveen** [neonwatty/machine-learning-refined#19]
Dear authors,
Thanks for a very nice book, which we are adopting for a new class starting in Feb'21.  It seems the Solutions at the Instructor Resources on the Cambridge Higher Education site are missing. There is a directory with zip files, but they contain the jpg images of the book (duplicate of the Figures directory).

**Comment by RezaBorhani** [comment]
@allejanvanderveen Thank you very much for bringing this issue to our attention! We are in contact with the publisher to fix it as soon as possible.

In the meantime you may consider using an alternative Cambridge University Press website that hosts the solutions as well as other instructor resources. Please go to[ this link](https://www.cambridge.org/us/academic/subjects/engineering/communications-and-signal-processing/machine-learning-refined-foundations-algorithms-and-applications-2nd-edition?format=HB), scroll down to the middle of the page, click on the **Resources** tab, and then on the **Solutions** tab on the left side-bar. I have verified that the solutions on this website are correct and up-to-date. And please do let us know if you still experience difficulty accessing the solutions.
