### ISSUE TITLE
Supplementary videos 

### ISSUE THREAD

**Issue by sergiovasquez122** [neonwatty/machine-learning-refined#20]
I have enjoyed working through the 2nd edition of the book, and I commend you for creating a machine learning book with such a good balance of intuition and rigor. I wondered if it would be viable down the road to include supplementary videos of the sections of the book? Something alongside the excellent videos by Caltech, which I will link below. Thanks again for the hard work!

https://home.work.caltech.edu/lectures.html

**Comment by neonwatty** [comment]
Please feel free so long as proper attribution is made!
