### ISSUE TITLE
Missing initialization in Exercise 6.5 MATLAB wrapper

### ISSUE THREAD

**Issue by Andrew-S-Rosen** [neonwatty/machine-learning-refined#3]
In the MATLAB wrapper for Exercise 6.5, the parameters `b`, `w`, `c`, and `V` used in the `tanh_softmax` function are not initialized. The code will not successfully run then even if `grad_b`, `grad_w`, `grad_c`, and `grad_V` are written correctly.

**Comment by RezaBorhani** [comment]
Thanks Andrew for pointing this out! It's been fixed now.
