### ISSUE TITLE
broken image on Vital_Elements_of_Calculus/All_about_derivatives_part_2

### ISSUE THREAD

**Issue by levibrown** [neonwatty/machine-learning-refined#4]
Seeing a broken image here: https://jermwatt.github.io/mlrefined/blog_posts/Vital_Elements_of_Calculus/All_about_derivatives_part_2.html
![screen shot 2017-07-24 at 9 52 28 pm](https://user-images.githubusercontent.com/83903/28556344-96404fb6-70ba-11e7-8a47-3651a75f97e4.png)

**Comment by neonwatty** [comment]
All fixed now.
