### ISSUE TITLE
pip install error-exist no requirements.txt: Mac Version 10.13.2

### ISSUE THREAD

**Issue by HaoyangHan** [neonwatty/machine-learning-refined#5]
I followed the instructions from **readme.md** and tried to install required packages as follows:

      git clone https://github.com/jermwatt/mlrefined
      cd mlrefined
      pip install -r requirements.txt

and Error showed saying that 

> Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'

And I couldn't find requirements.txt using search as well.

**Comment by neonwatty** [comment]
Apologies - I removed the text file in favor of suggesting an Anaconda install of Python 3, since this is generally easier.
