### ISSUE TITLE
ModuleNotFoundError: No module named 'autograd.misc'

### ISSUE THREAD

**Issue by fbglucky** [neonwatty/machine-learning-refined#6]
I run this code at the terminal: pip install autograd
but when I run the the below cell:
import sys
sys.path.append('../../')
import matplotlib.pyplot as plt
from mlrefined_libraries import basics_library as baslib
from mlrefined_libraries import linear_algebra_library as linlib

Then I got the below error:
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-3-dd74fc040c5f> in <module>()
      4 sys.path.append('../../')
      5 import matplotlib.pyplot as plt
----> 6 from mlrefined_libraries import basics_library as baslib
      7 from mlrefined_libraries import linear_algebra_library as linlib

/Volumes/DATA/projects/private/ml/mlrefined/mlrefined_libraries/__init__.py in <module>()
      7         prefix=__name__+'.',
      8         onerror=(lambda x: None)):
----> 9     __import__(modname)
     10 

/Volumes/DATA/projects/private/ml/mlrefined/mlrefined_libraries/convnets_library/convnet_lib/optimizers.py in <module>()
      2 from autograd import value_and_grad
      3 from autograd import hessian
----> 4 from autograd.misc.flatten import flatten_func
      5 from IPython.display import clear_output
      6 from timeit import default_timer as timer

ModuleNotFoundError: No module named 'autograd.misc'

I am using Anaconda with Python 3.6, I have no idea how to fix this issue. Can you check?

**Comment by neonwatty** [comment]
It looks like you need to update your version of autograd.
