### ISSUE TITLE
Figure numbering skips 6 in section 14.2

### ISSUE THREAD

**Issue by BrianMargolis** [neonwatty/machine-learning-refined#7]
[https://jermwatt.github.io/mlrefined/blog_posts/14_Convolutional_networks/14_2_Edge_histogram_based_features.html](https://jermwatt.github.io/mlrefined/blog_posts/14_Convolutional_networks/14_2_Edge_histogram_based_features.html)

Looks like it jumps from Figure 5 right to Figure 7

**Comment by neonwatty** [comment]
Thanks!
