### ISSUE TITLE
Automatic Differentiation is not available

### ISSUE THREAD

**Issue by shoaibkhanz** [neonwatty/machine-learning-refined#8]
Automatic Differentiation Section (chapter 2) is not available on the below website anymore. In what order should the website be read now. https://jermwatt.github.io/mlrefined/index.html

**Comment by neonwatty** [comment]
We are working on a major re-organization / addition to the content, and will be moving autodiff closer to the content on multilayer perceptrons.  For now I would start with Chapter 2 - on zero order methods - and move forward from there.

**Comment by shoaibkhanz** [comment]
Thanks for your response; I must say these notes are a lifesaver and one of the best notes I have found on the internet.
