### ISSUE TITLE
URL not working on Part 5: One-versus-All multi-class classification

### ISSUE THREAD

**Issue by ahmad-rameez** [neonwatty/machine-learning-refined#9]
The link to code at
https://jermwatt.github.io/mlrefined/blog_posts/Linear_Supervised_Learning/Part_5_One_versus_all.html
is note working.
Unable to open following link
https://github.com/jermwatt/mlrefined/blob/gh-pages/blog_posts/Linear_Supervised_Learning/Part_5_One_versus_all.ipynb

**Comment by neonwatty** [comment]
Thanks for the heads up!  Fixed.
